use anyhow::{Context, Result, anyhow};
pub mod bytes;
pub mod curves;
pub mod error;
pub mod formats;
pub mod model;
pub mod parser;
pub mod snarkjs;
pub mod verifier;

use crate::formats::{
    load_arkworks_inputs, load_arkworks_inputs_auto, load_compact_bundle, load_gnark_binary_inputs,
    load_gnark_binary_inputs_auto, load_gnark_json_inputs,
    load_snarkjs_json_inputs_with_optional_proof, load_sp1_groth16_inputs,
};
use crate::model::{
    CurveKind, Groth16G1Point, Groth16G2Point, Groth16Proof, Groth16VerifierInputs,
};
use std::{
    fs,
    path::{Path, PathBuf},
};

use ark_serialize::CanonicalSerialize;
use core::str::FromStr;

use ark_bls12_381::{
    Fq as Bls12Fq, Fq2 as Bls12Fq2, Fr as Bls12Fr, G1Affine as Bls12G1, G2Affine as Bls12G2,
};
use ark_bn254::{
    Fq as Bn254Fq, Fq2 as Bn254Fq2, Fr as Bn254Fr, G1Affine as Bn254G1, G2Affine as Bn254G2,
};

/// Elliptic curve selection for the verifier.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Curve {
    /// BLS12-381 curve (default)
    Bls12_381,
    /// BN254 curve (also known as BN128 or alt_bn128)
    Bn254,
}

impl Curve {
    fn as_curve_hint(self) -> &'static str {
        match self {
            Self::Bls12_381 => "bls12381",
            Self::Bn254 => "bn254",
        }
    }

    fn from_curve_kind(value: &CurveKind) -> Self {
        match value {
            CurveKind::Bn254 => Self::Bn254,
            CurveKind::Bls12_381 => Self::Bls12_381,
        }
    }
}

/// Soroban SDK dependency version for generated verifier crates.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum SorobanSdkVersion {
    /// Soroban SDK 26.x.
    V26,
    /// Soroban SDK 27.0.0-rc.1.
    #[default]
    V27,
}

impl SorobanSdkVersion {
    fn crate_version(self) -> &'static str {
        match self {
            Self::V26 => "26",
            Self::V27 => "27.0.0-rc.1",
        }
    }
}

/// Configuration options for generating a Soroban verifier contract.
#[derive(Debug, Clone)]
pub struct GenerateOptions {
    /// Path to the verification key JSON file (typically generated by circom/snarkjs).
    pub vk_json_path: PathBuf,
    /// Output directory where the contract crate will be generated.
    pub out_dir: PathBuf,
    /// Name of the generated crate (used in Cargo.toml).
    pub crate_name: String,
    /// Name of the contract struct in the generated code.
    pub contract_name: String,
    /// Elliptic curve to use (default: Bls12_381)
    pub curve: Curve,
}

/// Configuration options for generating a Soroban verifier contract from preloaded artifacts.
pub struct GenerateInputsOptions {
    /// Parsed verifier artifacts (VK + optional proof/public inputs).
    pub inputs: Groth16VerifierInputs,
    /// Output directory where the contract crate will be generated.
    pub out_dir: PathBuf,
    /// Name of the generated crate (used in Cargo.toml).
    pub crate_name: String,
    /// Name of the contract struct in the generated code.
    pub contract_name: String,
}

/// Generate a verifier contract from a snarkjs-style verification key.
///
/// This keeps backward compatibility with the original API.
pub fn generate_verifier_contract_to_dir(opts: GenerateOptions) -> Result<()> {
    let inputs = load_snarkjs_json_inputs_with_optional_proof(
        &opts.vk_json_path,
        None,
        None,
        Some(opts.curve.as_curve_hint()),
    )
    .context("failed to parse snarkjs inputs")?;

    generate_verifier_contract_from_inputs(GenerateInputsOptions {
        inputs,
        out_dir: opts.out_dir,
        crate_name: opts.crate_name,
        contract_name: opts.contract_name,
    })
}

/// Load verifier inputs from multiple artifact formats.
pub fn load_verifier_inputs(
    vk: Option<&Path>,
    proof: Option<&Path>,
    public: Option<&Path>,
    bundle: Option<&Path>,
    curve_hint: Option<&str>,
) -> Result<Groth16VerifierInputs> {
    match (bundle, vk) {
        (Some(_), Some(_)) => Err(anyhow!("use either --bundle or --vk, not both")),
        (Some(bundle), None) => {
            if proof.is_some() || public.is_some() {
                return Err(anyhow!("--bundle does not use --proof or --public"));
            }
            load_compact_bundle(bundle, curve_hint)
                .context("failed to load compact Arkworks bundle")
        }
        (None, Some(vk)) => load_inputs_auto(vk, proof, public, curve_hint),
        (None, None) => Err(anyhow!("--vk is required unless --bundle is used")),
    }
}

fn load_inputs_auto(
    vk: &Path,
    proof: Option<&Path>,
    public: Option<&Path>,
    curve_hint: Option<&str>,
) -> Result<Groth16VerifierInputs> {
    if let Some(curve_hint) = curve_hint {
        if let Err(err) = CurveKind::from_name(curve_hint) {
            return Err(anyhow!("unsupported curve hint {curve_hint}: {err}"));
        }

        if let Ok(inputs) =
            load_snarkjs_json_inputs_with_optional_proof(vk, proof, public, Some(curve_hint))
        {
            return Ok(inputs);
        }
        if let Ok(inputs) = load_gnark_json_inputs(vk, proof, public, Some(curve_hint)) {
            return Ok(inputs);
        }
        if let Ok(inputs) = load_arkworks_inputs(vk, proof, public, Some(curve_hint)) {
            return Ok(inputs);
        }
        if let Ok(inputs) = load_gnark_binary_inputs(vk, proof, public, curve_hint) {
            return Ok(inputs);
        }

        if let Some(proof) = proof
            && let Ok(inputs) = load_sp1_groth16_inputs(vk, proof)
        {
            return Ok(inputs);
        }

        return Err(anyhow!(
            "could not parse inputs for curve hint {curve_hint}"
        ));
    }

    let snarkjs_error = match load_snarkjs_json_inputs_with_optional_proof(vk, proof, public, None)
    {
        Ok(inputs) => return Ok(inputs),
        Err(err) => Some(err.to_string()),
    };

    let gnark_json_error = match load_gnark_json_inputs(vk, proof, public, None) {
        Ok(inputs) => return Ok(inputs),
        Err(err) => Some(err.to_string()),
    };

    let arkworks_error = match load_arkworks_inputs_auto(vk, proof, public) {
        Ok(inputs) => return Ok(inputs),
        Err(err) => Some(err.to_string()),
    };

    let gnark_binary_error = match load_gnark_binary_inputs_auto(vk, proof, public) {
        Ok(inputs) => return Ok(inputs),
        Err(err) => Some(err.to_string()),
    };

    if let Some(proof) = proof
        && let Ok(inputs) = load_sp1_groth16_inputs(vk, proof)
    {
        return Ok(inputs);
    }

    Err(anyhow!(
        "could not auto-detect input format: snarkjs failed: {}; gnark json failed: {}; arkworks failed: {}; gnark binary failed: {}; sp1 failed or was not attempted",
        snarkjs_error
            .map(|e| e.to_string())
            .unwrap_or_else(|| "unknown".to_string()),
        gnark_json_error
            .map(|e| e.to_string())
            .unwrap_or_else(|| "unknown".to_string()),
        arkworks_error
            .map(|e| e.to_string())
            .unwrap_or_else(|| "unknown".to_string()),
        gnark_binary_error
            .map(|e| e.to_string())
            .unwrap_or_else(|| "unknown".to_string()),
    ))
}

fn bytes_from_curve_g1(curve: Curve, point: &Groth16G1Point) -> Result<Vec<u8>> {
    match curve {
        Curve::Bls12_381 => bls12_g1_uncompressed_bytes(point),
        Curve::Bn254 => bn254_g1_uncompressed_bytes(point),
    }
}

fn bytes_from_curve_g2(curve: Curve, point: &Groth16G2Point) -> Result<Vec<u8>> {
    match curve {
        Curve::Bls12_381 => bls12_g2_uncompressed_bytes(point),
        Curve::Bn254 => bn254_g2_uncompressed_bytes(point),
    }
}

struct EmbeddedTestVectors {
    proof_a: Vec<u8>,
    proof_b: Vec<u8>,
    proof_c: Vec<u8>,
    public_inputs: Vec<Vec<u8>>,
}

impl EmbeddedTestVectors {
    fn from_proof(curve: Curve, proof: &Groth16Proof, public_inputs: &[String]) -> Result<Self> {
        Ok(Self {
            proof_a: bytes_from_curve_g1(curve, &proof.pi_a)?,
            proof_b: bytes_from_curve_g2(curve, &proof.pi_b)?,
            proof_c: bytes_from_curve_g1(curve, &proof.pi_c)?,
            public_inputs: public_inputs
                .iter()
                .map(|value| fr_bytes_from_curve(curve, value))
                .collect::<Result<Vec<_>>>()?,
        })
    }
}

fn fr_bytes_from_curve(curve: Curve, value: &str) -> Result<Vec<u8>> {
    match curve {
        Curve::Bls12_381 => fr_bytes_be::<Bls12Fr>(value, "BLS12-381"),
        Curve::Bn254 => fr_bytes_be::<Bn254Fr>(value, "BN254"),
    }
}

fn fr_bytes_be<F>(value: &str, curve: &str) -> Result<Vec<u8>>
where
    F: ark_ff::PrimeField,
{
    use ark_ff::BigInteger;

    let scalar =
        F::from_str(value).map_err(|_| anyhow!("bad {curve} scalar public input: {value}"))?;
    let bytes = scalar.into_bigint().to_bytes_be();
    let mut out = vec![0u8; 32];
    let start = out.len().saturating_sub(bytes.len());
    out[start..].copy_from_slice(&bytes);
    Ok(out)
}

fn bls12_g1_uncompressed_bytes(point: &Groth16G1Point) -> Result<Vec<u8>> {
    let x = Bls12Fq::from_str(&point.x).map_err(|_| anyhow!("bad Fq x"))?;
    let y = Bls12Fq::from_str(&point.y).map_err(|_| anyhow!("bad Fq y"))?;
    let p = Bls12G1::new(x, y);
    let mut out = vec![];
    p.serialize_uncompressed(&mut out)
        .map_err(|e| anyhow!("failed to serialize BLS12-381 G1: {e}"))?;
    Ok(out)
}

fn bls12_g2_uncompressed_bytes(point: &Groth16G2Point) -> Result<Vec<u8>> {
    let x = Bls12Fq2::new(
        Bls12Fq::from_str(&point.x0).map_err(|_| anyhow!("bad Fq x0"))?,
        Bls12Fq::from_str(&point.x1).map_err(|_| anyhow!("bad Fq x1"))?,
    );
    let y = Bls12Fq2::new(
        Bls12Fq::from_str(&point.y0).map_err(|_| anyhow!("bad Fq y0"))?,
        Bls12Fq::from_str(&point.y1).map_err(|_| anyhow!("bad Fq y1"))?,
    );
    let p = Bls12G2::new(x, y);
    let mut out = vec![];
    p.serialize_uncompressed(&mut out)
        .map_err(|e| anyhow!("failed to serialize BLS12-381 G2: {e}"))?;
    Ok(out)
}

fn fq_to_bytes_be(fq: &Bn254Fq) -> Vec<u8> {
    use ark_ff::{BigInteger, PrimeField};
    let bytes = fq.into_bigint().to_bytes_be();
    let mut out = vec![0u8; 32];
    let start = out.len().saturating_sub(bytes.len());
    out[start..].copy_from_slice(&bytes);
    out
}

fn bn254_g1_uncompressed_bytes(point: &Groth16G1Point) -> Result<Vec<u8>> {
    let x = Bn254Fq::from_str(&point.x).map_err(|_| anyhow!("bad Fq x for BN254"))?;
    let y = Bn254Fq::from_str(&point.y).map_err(|_| anyhow!("bad Fq y for BN254"))?;
    let p = Bn254G1::new(x, y);
    Ok([&fq_to_bytes_be(&p.x)[..], &fq_to_bytes_be(&p.y)[..]].concat())
}

fn bn254_g2_uncompressed_bytes(point: &Groth16G2Point) -> Result<Vec<u8>> {
    let x = Bn254Fq2::new(
        Bn254Fq::from_str(&point.x0).map_err(|_| anyhow!("bad Fq x0 for BN254"))?,
        Bn254Fq::from_str(&point.x1).map_err(|_| anyhow!("bad Fq x1 for BN254"))?,
    );
    let y = Bn254Fq2::new(
        Bn254Fq::from_str(&point.y0).map_err(|_| anyhow!("bad Fq y0 for BN254"))?,
        Bn254Fq::from_str(&point.y1).map_err(|_| anyhow!("bad Fq y1 for BN254"))?,
    );
    let p = Bn254G2::new(x, y);

    let mut out = Vec::with_capacity(128);
    out.extend_from_slice(&fq_to_bytes_be(&p.x.c1));
    out.extend_from_slice(&fq_to_bytes_be(&p.x.c0));
    out.extend_from_slice(&fq_to_bytes_be(&p.y.c1));
    out.extend_from_slice(&fq_to_bytes_be(&p.y.c0));
    Ok(out)
}

fn fmt_u8_list(bytes: &[u8]) -> String {
    bytes
        .iter()
        .map(|b| format!("0x{:02x}", b))
        .collect::<Vec<_>>()
        .join(", ")
}

fn emit_const(name: &str, size_expr: &str, bytes: &[u8]) -> String {
    format!(
        "const {name}: [u8; {size}] = [{vals}];\n",
        name = name,
        size = size_expr,
        vals = fmt_u8_list(bytes)
    )
}

// ponytail: flat private renderer args beat a one-use config struct.
#[allow(clippy::too_many_arguments)]
fn render_contract_source(
    contract_name: &str,
    curve: Curve,
    alpha: &[u8],
    beta: &[u8],
    gamma: &[u8],
    delta: &[u8],
    ic: &[Vec<u8>],
    test_vectors: Option<&EmbeddedTestVectors>,
) -> String {
    let mut s = String::new();

    s.push_str("#![no_std]\n");
    s.push_str("use soroban_sdk::{\n");
    s.push_str("    contract, contracterror, contractimpl, contracttype,\n");

    match curve {
        Curve::Bls12_381 => {
            s.push_str("    crypto::bls12_381::{Bls12381Fr, Bls12381G1Affine, Bls12381G2Affine, G1_SERIALIZED_SIZE, G2_SERIALIZED_SIZE},\n");
        }
        Curve::Bn254 => {
            s.push_str("    crypto::bn254::{Bn254Fr, Bn254G1Affine, Bn254G2Affine, BN254_G1_SERIALIZED_SIZE, BN254_G2_SERIALIZED_SIZE},\n");
        }
    }

    s.push_str("    Env, Vec,\n");
    s.push_str("};\n\n");

    s.push_str("#[contracterror]\n");
    s.push_str("#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]\n");
    s.push_str("#[repr(u32)]\n");
    s.push_str("pub enum Groth16Error {\n");
    s.push_str("    MalformedVerifyingKey = 0,\n");
    s.push_str("}\n\n");

    let (g1_type, g2_type) = match curve {
        Curve::Bls12_381 => ("Bls12381G1Affine", "Bls12381G2Affine"),
        Curve::Bn254 => ("Bn254G1Affine", "Bn254G2Affine"),
    };
    let fr_type = match curve {
        Curve::Bls12_381 => "Bls12381Fr",
        Curve::Bn254 => "Bn254Fr",
    };

    s.push_str("#[derive(Clone)]\n#[contracttype]\n");
    s.push_str("pub struct VerificationKey {\n");
    s.push_str(&format!("    pub alpha: {},\n", g1_type));
    s.push_str(&format!("    pub beta: {},\n", g2_type));
    s.push_str(&format!("    pub gamma: {},\n", g2_type));
    s.push_str(&format!("    pub delta: {},\n", g2_type));
    s.push_str(&format!("    pub ic: Vec<{}>,\n", g1_type));
    s.push_str("}\n\n");

    s.push_str("#[derive(Clone)]\n#[contracttype]\n");
    s.push_str("pub struct Proof {\n");
    s.push_str(&format!("    pub a: {},\n", g1_type));
    s.push_str(&format!("    pub b: {},\n", g2_type));
    s.push_str(&format!("    pub c: {},\n", g1_type));
    s.push_str("}\n\n");

    let (g1_size, g2_size) = match curve {
        Curve::Bls12_381 => ("G1_SERIALIZED_SIZE", "G2_SERIALIZED_SIZE"),
        Curve::Bn254 => ("BN254_G1_SERIALIZED_SIZE", "BN254_G2_SERIALIZED_SIZE"),
    };

    s.push_str("// AUTO-GENERATED VK BYTES (uncompressed). DO NOT EDIT.\n");
    s.push_str(&emit_const("VK_ALPHA", g1_size, alpha));
    s.push_str(&emit_const("VK_BETA", g2_size, beta));
    s.push_str(&emit_const("VK_GAMMA", g2_size, gamma));
    s.push_str(&emit_const("VK_DELTA", g2_size, delta));
    s.push('\n');

    s.push_str(&format!(
        "const VK_IC: [[u8; {}]; {}] = [\n",
        g1_size,
        ic.len()
    ));
    for b in ic {
        s.push_str("    [");
        s.push_str(&fmt_u8_list(b));
        s.push_str("],\n");
    }
    s.push_str("];\n\n");

    if let Some(vectors) = test_vectors {
        s.push_str("// AUTO-GENERATED TEST VECTOR BYTES (uncompressed). DO NOT EDIT.\n");
        s.push_str("#[cfg(test)]\n");
        s.push_str(&emit_const("TEST_PROOF_A", g1_size, &vectors.proof_a));
        s.push_str("#[cfg(test)]\n");
        s.push_str(&emit_const("TEST_PROOF_B", g2_size, &vectors.proof_b));
        s.push_str("#[cfg(test)]\n");
        s.push_str(&emit_const("TEST_PROOF_C", g1_size, &vectors.proof_c));
        s.push_str("#[cfg(test)]\n");
        s.push_str(&format!(
            "const TEST_PUBLIC_INPUTS: [[u8; 32]; {}] = [\n",
            vectors.public_inputs.len()
        ));
        for input in &vectors.public_inputs {
            s.push_str("    [");
            s.push_str(&fmt_u8_list(input));
            s.push_str("],\n");
        }
        s.push_str("];\n\n");
    }

    s.push_str("fn vk(env: &Env) -> VerificationKey {\n");
    s.push_str(&format!(
        "    let alpha = {}::from_array(env, &VK_ALPHA);\n",
        g1_type
    ));
    s.push_str(&format!(
        "    let beta  = {}::from_array(env, &VK_BETA);\n",
        g2_type
    ));
    s.push_str(&format!(
        "    let gamma = {}::from_array(env, &VK_GAMMA);\n",
        g2_type
    ));
    s.push_str(&format!(
        "    let delta = {}::from_array(env, &VK_DELTA);\n\n",
        g2_type
    ));
    s.push_str("    let mut ic = Vec::new(env);\n");
    s.push_str("    for p in VK_IC.iter() {\n");
    s.push_str(&format!(
        "        ic.push_back({}::from_array(env, p));\n",
        g1_type
    ));
    s.push_str("    }\n\n");
    s.push_str("    VerificationKey { alpha, beta, gamma, delta, ic }\n");
    s.push_str("}\n\n");

    s.push_str("#[contract]\n");
    s.push_str(&format!("pub struct {};", contract_name));
    s.push_str("\n\n");

    s.push_str("#[contractimpl]\n");
    s.push_str(&format!("impl {} {{\n", contract_name));
    s.push_str(&format!(
        "    pub fn verify_proof(env: Env, proof: Proof, pub_signals: Vec<{}>) -> Result<bool, Groth16Error> {{\n",
        fr_type
    ));

    match curve {
        Curve::Bls12_381 => s.push_str("        let bls = env.crypto().bls12_381();\n"),
        Curve::Bn254 => s.push_str("        let bn = env.crypto().bn254();\n"),
    }

    s.push_str("        let vk = vk(&env);\n\n");
    s.push_str("        if pub_signals.len() + 1 != vk.ic.len() {\n");
    s.push_str("            return Err(Groth16Error::MalformedVerifyingKey);\n");
    s.push_str("        }\n\n");
    s.push_str("        let mut vk_x = vk.ic.get(0).unwrap();\n");
    s.push_str("        for (s, v) in pub_signals.iter().zip(vk.ic.iter().skip(1)) {\n");
    match curve {
        Curve::Bls12_381 => {
            s.push_str("            let prod = bls.g1_mul(&v, &s);\n");
            s.push_str("            vk_x = bls.g1_add(&vk_x, &prod);\n");
        }
        Curve::Bn254 => {
            s.push_str("            let prod = bn.g1_mul(&v, &s);\n");
            s.push_str("            vk_x = bn.g1_add(&vk_x, &prod);\n");
        }
    }
    s.push_str("        }\n\n");
    s.push_str("        let neg_a = -proof.a;\n");
    s.push_str("        let vp1 = soroban_sdk::vec![&env, neg_a, vk.alpha, vk_x, proof.c];\n");
    s.push_str(
        "        let vp2 = soroban_sdk::vec![&env, proof.b, vk.beta, vk.gamma, vk.delta];\n\n",
    );

    match curve {
        Curve::Bls12_381 => s.push_str("        Ok(bls.pairing_check(vp1, vp2))\n"),
        Curve::Bn254 => s.push_str("        Ok(bn.pairing_check(vp1, vp2))\n"),
    }

    s.push_str("    }\n");
    s.push_str("}\n");
    s.push_str("\n#[cfg(test)]\n");
    s.push_str("mod test {\n");
    s.push_str("    use super::*;\n");
    s.push_str("    use soroban_sdk::BytesN;\n\n");
    s.push_str("    #[test]\n");
    s.push_str("    fn rejects_wrong_public_input_count() {\n");
    s.push_str("        let env = Env::default();\n");
    s.push_str(&format!(
        "        let proof = Proof {{ a: {}::from_array(&env, &VK_ALPHA), b: {}::from_array(&env, &VK_BETA), c: {}::from_array(&env, &VK_ALPHA) }};\n",
        g1_type, g2_type, g1_type
    ));
    s.push_str("        let mut pub_signals = Vec::new(&env);\n");
    s.push_str("        for _ in 0..VK_IC.len() {\n");
    s.push_str(&format!(
        "            pub_signals.push_back({}::from_bytes(BytesN::from_array(&env, &[0u8; 32])));\n",
        fr_type
    ));
    s.push_str("        }\n\n");
    s.push_str(&format!(
        "        assert_eq!({}::verify_proof(env, proof, pub_signals), Err(Groth16Error::MalformedVerifyingKey));\n",
        contract_name
    ));
    s.push_str("    }\n");
    if test_vectors.is_some() {
        s.push_str("\n    #[test]\n");
        s.push_str("    fn verifies_embedded_test_vectors() {\n");
        s.push_str("        let env = Env::default();\n");
        s.push_str(&format!(
            "        let proof = Proof {{ a: {}::from_array(&env, &TEST_PROOF_A), b: {}::from_array(&env, &TEST_PROOF_B), c: {}::from_array(&env, &TEST_PROOF_C) }};\n",
            g1_type, g2_type, g1_type
        ));
        s.push_str("        let mut pub_signals = Vec::new(&env);\n");
        s.push_str("        for input in TEST_PUBLIC_INPUTS.iter() {\n");
        s.push_str(&format!(
            "            pub_signals.push_back({}::from_bytes(BytesN::from_array(&env, input)));\n",
            fr_type
        ));
        s.push_str("        }\n\n");
        s.push_str(&format!(
            "        assert_eq!({}::verify_proof(env, proof, pub_signals), Ok(true));\n",
            contract_name
        ));
        s.push_str("    }\n");
    }
    s.push_str("}\n");

    s
}

fn render_contract_cargo_toml(
    crate_name: &str,
    curve: Curve,
    sdk_version: SorobanSdkVersion,
) -> String {
    let ark_curve = match curve {
        Curve::Bls12_381 => "ark-bls12-381 = \"0.6\"",
        Curve::Bn254 => "ark-bn254 = \"0.6\"",
    };
    let sdk_version = sdk_version.crate_version();

    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = "{sdk_version}"

[dev-dependencies]
soroban-sdk = {{ version = "{sdk_version}", features = ["testutils"] }}
{ark_curve}
ark-ff = "0.6"
ark-serialize = "0.6"
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"

[profile.release]
overflow-checks = true
"#
    )
}

/// Generate a verifier contract from preloaded inputs.
pub fn generate_verifier_contract_from_inputs(opts: GenerateInputsOptions) -> Result<()> {
    generate_verifier_contract_from_inputs_with_sdk(opts, SorobanSdkVersion::default())
}

/// Generate a verifier contract from preloaded inputs for a specific Soroban SDK version.
pub fn generate_verifier_contract_from_inputs_with_sdk(
    opts: GenerateInputsOptions,
    sdk_version: SorobanSdkVersion,
) -> Result<()> {
    let curve = Curve::from_curve_kind(&opts.inputs.curve);
    let n_public = opts
        .inputs
        .verifying_key
        .ic
        .len()
        .checked_sub(1)
        .ok_or_else(|| anyhow!("invalid verifying key: IC list is empty"))?;

    if n_public != opts.inputs.verifying_key.n_public {
        return Err(anyhow!(
            "invalid verifying key: expected n_public {} but got {}",
            opts.inputs.verifying_key.n_public,
            n_public
        ));
    }

    let alpha = bytes_from_curve_g1(curve, &opts.inputs.verifying_key.vk_alpha_1)?;
    let beta = bytes_from_curve_g2(curve, &opts.inputs.verifying_key.vk_beta_2)?;
    let gamma = bytes_from_curve_g2(curve, &opts.inputs.verifying_key.vk_gamma_2)?;
    let delta = bytes_from_curve_g2(curve, &opts.inputs.verifying_key.vk_delta_2)?;

    let mut ic_bytes = Vec::with_capacity(opts.inputs.verifying_key.ic.len());
    for point in &opts.inputs.verifying_key.ic {
        ic_bytes.push(bytes_from_curve_g1(curve, point)?);
    }

    if ic_bytes.len() != n_public + 1 {
        return Err(anyhow!(
            "invalid verifying key: expected IC count {} got {}",
            n_public + 1,
            ic_bytes.len()
        ));
    }

    let test_vectors = opts
        .inputs
        .proof
        .as_ref()
        .map(|proof| EmbeddedTestVectors::from_proof(curve, proof, &opts.inputs.public_inputs))
        .transpose()?;

    let lib_rs = render_contract_source(
        &opts.contract_name,
        curve,
        &alpha,
        &beta,
        &gamma,
        &delta,
        &ic_bytes,
        test_vectors.as_ref(),
    );
    let cargo_toml = render_contract_cargo_toml(&opts.crate_name, curve, sdk_version);

    write_file(&opts.out_dir.join("Cargo.toml"), &cargo_toml)?;
    write_file(&opts.out_dir.join("src").join("lib.rs"), &lib_rs)?;
    Ok(())
}

fn write_file(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create directory {}", path.display()))?;
    }
    fs::write(path, contents)
        .with_context(|| format!("failed to write file {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{
        Curve, EmbeddedTestVectors, SorobanSdkVersion, render_contract_cargo_toml,
        render_contract_source,
    };

    #[test]
    fn generated_contract_cargo_toml_targets_soroban_sdk_27_by_default() {
        for curve in [Curve::Bls12_381, Curve::Bn254] {
            let cargo_toml =
                render_contract_cargo_toml("verifier", curve, SorobanSdkVersion::default());
            assert!(cargo_toml.contains("soroban-sdk = \"27.0.0-rc.1\""));
            assert!(cargo_toml.contains(
                "soroban-sdk = { version = \"27.0.0-rc.1\", features = [\"testutils\"] }"
            ));
            assert!(cargo_toml.contains("[workspace]"));
            assert!(cargo_toml.contains("[profile.release]"));
            assert!(cargo_toml.contains("overflow-checks = true"));
        }
    }

    #[test]
    fn generated_contract_cargo_toml_can_target_soroban_sdk_26() {
        for curve in [Curve::Bls12_381, Curve::Bn254] {
            let cargo_toml = render_contract_cargo_toml("verifier", curve, SorobanSdkVersion::V26);
            assert!(cargo_toml.contains("soroban-sdk = \"26\""));
            assert!(
                cargo_toml
                    .contains("soroban-sdk = { version = \"26\", features = [\"testutils\"] }")
            );
            assert!(cargo_toml.contains("[workspace]"));
            assert!(cargo_toml.contains("[profile.release]"));
            assert!(cargo_toml.contains("overflow-checks = true"));
        }
    }

    #[test]
    fn generated_contract_source_uses_soroban_26_type_names() {
        let bls_source = render_contract_source(
            "Verifier",
            Curve::Bls12_381,
            &[],
            &[],
            &[],
            &[],
            &[vec![]],
            None,
        );
        assert!(bls_source.contains("Bls12381Fr"));
        assert!(bls_source.contains("Bls12381G1Affine"));
        assert!(bls_source.contains("Bls12381G2Affine"));
        assert!(bls_source.contains("fn rejects_wrong_public_input_count()"));

        let bn254_source = render_contract_source(
            "Verifier",
            Curve::Bn254,
            &[],
            &[],
            &[],
            &[],
            &[vec![]],
            None,
        );
        assert!(bn254_source.contains("Bn254Fr"));
        assert!(bn254_source.contains("Bn254G1Affine"));
        assert!(bn254_source.contains("Bn254G2Affine"));
        assert!(bn254_source.contains("fn rejects_wrong_public_input_count()"));
    }

    #[test]
    fn generated_contract_source_embeds_positive_test_vectors_when_available() {
        let vectors = EmbeddedTestVectors {
            proof_a: vec![1; 96],
            proof_b: vec![2; 192],
            proof_c: vec![3; 96],
            public_inputs: vec![vec![4; 32]],
        };
        let source = render_contract_source(
            "Verifier",
            Curve::Bls12_381,
            &[0; 96],
            &[0; 192],
            &[0; 192],
            &[0; 192],
            &[vec![0; 96], vec![0; 96]],
            Some(&vectors),
        );

        assert!(source.contains("const TEST_PROOF_A"));
        assert!(source.contains("const TEST_PUBLIC_INPUTS"));
        assert!(source.contains("fn verifies_embedded_test_vectors()"));
        assert!(
            source
                .contains("assert_eq!(Verifier::verify_proof(env, proof, pub_signals), Ok(true));")
        );
    }
}
